"""
This program is used to generate two-shot images for the YOLO model.
The two-shot images are generated by taking two images and combining them into one.
"""

import os
from ultralytics import YOLO

"""
set global variables
"""
current_dir = os.path.dirname(__file__)
INPUT_DIR = os.path.join(current_dir, "input")
OUTPUT_DIR = os.path.join(current_dir, "output")
MODEL_DIR = os.path.join(current_dir, "models")

CHARACTER_IMG_DIR = os.path.join(INPUT_DIR, "character_img")
HUMAN_IMG_DIR = os.path.join(INPUT_DIR, "human_img")

face_detect_model = YOLO(os.path.join(MODEL_DIR, "yolov8n-face.pt"))

def get_prediction_results(model: YOLO, img_dir: str, **predict_kwargs):
    """
    This function is used to get the prediction results from the YOLO model.
    """
    img_names = os.listdir(img_dir)
    results = []
    for img_name in img_names:
        img_path = os.path.join(img_dir, img_name)
        results.append(model.predict(img_path, **predict_kwargs))
    return results

if __name__ == "__main__":
    character_results = get_prediction_results(face_detect_model, os.path.join(INPUT_DIR, CHARACTER_IMG_DIR), show=True)
    human_results = get_prediction_results(face_detect_model, os.path.join(INPUT_DIR, HUMAN_IMG_DIR), show=True)

    for human_result in human_results:
        print(human_result[0].boxes[0].xywh)
        print(human_result[0].boxes[0].xywh)
    
    